<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\clokr.ico</ApplicationIcon>
    <AssemblyName>Clokr</AssemblyName>
    <RootNamespace>Clokr</RootNamespace>
    <Description>CPU Frequency Manager for Hybrid Core Processors</Description>
    <Company>hadouken</Company>
    <Product>Clokr</Product>
    <Copyright>Copyright (C) 2026 hadouken</Copyright>
    <Version>1.0.5</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="System.Management" Version="4.7.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.1">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
